### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by bigmosi** [RitobrotoMukherjee/portfolio-bootstrap-five#2]
- Your project looks professional and the codebase looks fine. Only the I want to comment that You should update your ReadMe file. ReadMe file helps another developer to easily understand your project.
- Please make it more responsive especially on smaller screens.

**Comment by RitobrotoMukherjee** [comment]
### Thanks folks for your kind reviews.

- Fixed the MD
- Made responsive for the smaller screens.

**Comment by RitobrotoMukherjee** [comment]
> * Your project looks professional and the codebase looks fine. Only the I want to comment that You should update your ReadMe file. ReadMe file helps another developer to easily understand your project.
> * Please make it more responsive especially on smaller screens.

### Thanks @bigmosi for your kind reviews.

- Fixed the MD
- Made responsive for the smaller screens.
